spring.application.name=SpringSecurityBasic

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/springBoot?createDatabaseIfNoExist=true
spring.datasource.username=root
spring.datasource.password=Svarunkumar@09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.user.name=user
spring.security.user.password=varun